excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ilanmichalby.github.io
title: mindcet vr
email: ilanmichalby@gmail.com
author: Ilan Ben Yaakov
description: vr with mindcet
paginate: 3
google_analytics: 